# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
import baml_py

from . import stream_types, types, type_builder
from .parser import LlmResponseParser, LlmStreamParser
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME as __runtime__

class BamlSyncClient:
    __options: DoNotUseDirectlyCallManager
    __stream_client: "BamlStreamClient"
    __http_request: "BamlHttpRequestClient"
    __http_stream_request: "BamlHttpStreamRequestClient"
    __llm_response_parser: LlmResponseParser
    __llm_stream_parser: LlmStreamParser

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options
        self.__stream_client = BamlStreamClient(options)
        self.__http_request = BamlHttpRequestClient(options)
        self.__http_stream_request = BamlHttpStreamRequestClient(options)
        self.__llm_response_parser = LlmResponseParser(options)
        self.__llm_stream_parser = LlmStreamParser(options)

    def __getstate__(self):
        # Return state needed for pickling
        return {"options": self.__options}

    def __setstate__(self, state):
        # Restore state from pickling
        self.__options = state["options"]
        self.__stream_client = BamlStreamClient(self.__options)
        self.__http_request = BamlHttpRequestClient(self.__options)
        self.__http_stream_request = BamlHttpStreamRequestClient(self.__options)
        self.__llm_response_parser = LlmResponseParser(self.__options)
        self.__llm_stream_parser = LlmStreamParser(self.__options)

    def with_options(self,
        tb: typing.Optional[type_builder.TypeBuilder] = None,
        client_registry: typing.Optional[baml_py.baml_py.ClientRegistry] = None,
        collector: typing.Optional[typing.Union[baml_py.baml_py.Collector, typing.List[baml_py.baml_py.Collector]]] = None,
        env: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None,
    ) -> "BamlSyncClient":
        options: BamlCallOptions = {}
        if tb is not None:
            options["tb"] = tb
        if client_registry is not None:
            options["client_registry"] = client_registry
        if collector is not None:
            options["collector"] = collector
        if env is not None:
            options["env"] = env
        return BamlSyncClient(self.__options.merge_options(options))

    @property
    def stream(self):
      return self.__stream_client

    @property
    def request(self):
      return self.__http_request

    @property
    def stream_request(self):
      return self.__http_stream_request

    @property
    def parse(self):
      return self.__llm_response_parser

    @property
    def parse_stream(self):
      return self.__llm_stream_parser
    
    def GenerateCoverageTests(self, source_code: str,analysis: types.CoverageAnalysis,
        baml_options: BamlCallOptions = {},
    ) -> types.PythonTestFile:
        result = self.__options.merge_options(baml_options).call_function_sync(function_name="GenerateCoverageTests", args={
            "source_code": source_code,"analysis": analysis,
        })
        return typing.cast(types.PythonTestFile, result.cast_to(types, types, stream_types, False, __runtime__))
    def GenerateFuzzInputs(self, source_code: str,
        baml_options: BamlCallOptions = {},
    ) -> typing.List["types.FuzzInput"]:
        result = self.__options.merge_options(baml_options).call_function_sync(function_name="GenerateFuzzInputs", args={
            "source_code": source_code,
        })
        return typing.cast(typing.List["types.FuzzInput"], result.cast_to(types, types, stream_types, False, __runtime__))
    def GenerateTests(self, source_code: str,
        baml_options: BamlCallOptions = {},
    ) -> types.PythonTestFile:
        result = self.__options.merge_options(baml_options).call_function_sync(function_name="GenerateTests", args={
            "source_code": source_code,
        })
        return typing.cast(types.PythonTestFile, result.cast_to(types, types, stream_types, False, __runtime__))
    


class BamlStreamClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def GenerateCoverageTests(self, source_code: str,analysis: types.CoverageAnalysis,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.PythonTestFile, types.PythonTestFile]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="GenerateCoverageTests", args={
            "source_code": source_code,"analysis": analysis,
        })
        return baml_py.BamlSyncStream[stream_types.PythonTestFile, types.PythonTestFile](
          result,
          lambda x: typing.cast(stream_types.PythonTestFile, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.PythonTestFile, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def GenerateFuzzInputs(self, source_code: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[typing.List["stream_types.FuzzInput"], typing.List["types.FuzzInput"]]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="GenerateFuzzInputs", args={
            "source_code": source_code,
        })
        return baml_py.BamlSyncStream[typing.List["stream_types.FuzzInput"], typing.List["types.FuzzInput"]](
          result,
          lambda x: typing.cast(typing.List["stream_types.FuzzInput"], x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(typing.List["types.FuzzInput"], x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def GenerateTests(self, source_code: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.PythonTestFile, types.PythonTestFile]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="GenerateTests", args={
            "source_code": source_code,
        })
        return baml_py.BamlSyncStream[stream_types.PythonTestFile, types.PythonTestFile](
          result,
          lambda x: typing.cast(stream_types.PythonTestFile, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.PythonTestFile, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    

class BamlHttpRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def GenerateCoverageTests(self, source_code: str,analysis: types.CoverageAnalysis,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="GenerateCoverageTests", args={
            "source_code": source_code,"analysis": analysis,
        }, mode="request")
        return result
    def GenerateFuzzInputs(self, source_code: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="GenerateFuzzInputs", args={
            "source_code": source_code,
        }, mode="request")
        return result
    def GenerateTests(self, source_code: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="GenerateTests", args={
            "source_code": source_code,
        }, mode="request")
        return result
    

class BamlHttpStreamRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def GenerateCoverageTests(self, source_code: str,analysis: types.CoverageAnalysis,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="GenerateCoverageTests", args={
            "source_code": source_code,"analysis": analysis,
        }, mode="stream")
        return result
    def GenerateFuzzInputs(self, source_code: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="GenerateFuzzInputs", args={
            "source_code": source_code,
        }, mode="stream")
        return result
    def GenerateTests(self, source_code: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="GenerateTests", args={
            "source_code": source_code,
        }, mode="stream")
        return result
    

b = BamlSyncClient(DoNotUseDirectlyCallManager({}))