# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.CoverageAnalysis": types.CoverageAnalysis,
    "stream_types.CoverageAnalysis": stream_types.CoverageAnalysis,

    "types.FuzzInput": types.FuzzInput,
    "stream_types.FuzzInput": stream_types.FuzzInput,

    "types.MutationAnalysis": types.MutationAnalysis,
    "stream_types.MutationAnalysis": stream_types.MutationAnalysis,

    "types.PythonTestFile": types.PythonTestFile,
    "stream_types.PythonTestFile": stream_types.PythonTestFile,

    "types.TestCase": types.TestCase,
    "stream_types.TestCase": stream_types.TestCase,


}