# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.CoverageImprovement": types.CoverageImprovement,
    "stream_types.CoverageImprovement": stream_types.CoverageImprovement,

    "types.CrashAnalysis": types.CrashAnalysis,
    "stream_types.CrashAnalysis": stream_types.CrashAnalysis,

    "types.FuzzTestInput": types.FuzzTestInput,
    "stream_types.FuzzTestInput": stream_types.FuzzTestInput,

    "types.Mutant": types.Mutant,
    "stream_types.Mutant": stream_types.Mutant,

    "types.MutationOperator": types.MutationOperator,
    "stream_types.MutationOperator": stream_types.MutationOperator,

    "types.MutationReport": types.MutationReport,
    "stream_types.MutationReport": stream_types.MutationReport,

    "types.MutationResult": types.MutationResult,
    "stream_types.MutationResult": stream_types.MutationResult,

    "types.MutationStrategy": types.MutationStrategy,
    "stream_types.MutationStrategy": stream_types.MutationStrategy,

    "types.UnitTestCase": types.UnitTestCase,
    "stream_types.UnitTestCase": stream_types.UnitTestCase,


}