# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (0)
# #########################################################################

# #########################################################################
# Generated classes (9)
# #########################################################################

class CoverageImprovement(BaseModel):
    file_path: str
    function_name: str
    current_coverage_percentage: float
    suggestion_type: typing.Union[typing_extensions.Literal['missing_tests'], typing_extensions.Literal['edge_cases'], typing_extensions.Literal['error_handling']]
    priority: typing.Union[typing_extensions.Literal['low'], typing_extensions.Literal['medium'], typing_extensions.Literal['high']]
    suggested_tests: typing.List[str]
    code_examples: typing.List[str]

class CrashAnalysis(BaseModel):
    root_cause: str
    severity: typing.Union[typing_extensions.Literal['low'], typing_extensions.Literal['medium'], typing_extensions.Literal['high'], typing_extensions.Literal['critical']]
    suggested_fix: str
    additional_test_cases: typing.List[str]

class FuzzTestInput(BaseModel):
    args: typing.List[typing.Optional[typing.Union[str, int, float, bool]]]
    kwargs: typing.Dict[str, typing.Optional[typing.Union[str, int, float, bool]]]
    description: str
    expected_behavior: typing.Union[typing_extensions.Literal['normal'], typing_extensions.Literal['error'], typing_extensions.Literal['edge_case']]

class Mutant(BaseModel):
    id: str
    operator_name: str
    original_code: str
    mutated_code: str
    line_number: int
    column_number: int
    function_name: str
    description: str

class MutationOperator(BaseModel):
    name: str
    description: str
    category: typing.Union[typing_extensions.Literal['arithmetic'], typing_extensions.Literal['comparison'], typing_extensions.Literal['logical'], typing_extensions.Literal['boolean'], typing_extensions.Literal['constant'], typing_extensions.Literal['statement']]
    original_pattern: str
    mutated_pattern: str
    risk_level: typing.Union[typing_extensions.Literal['low'], typing_extensions.Literal['medium'], typing_extensions.Literal['high']]

class MutationReport(BaseModel):
    total_mutants: int
    killed_mutants: int
    survived_mutants: int
    timeout_mutants: int
    error_mutants: int
    mutation_score: float
    function_scores: typing.Dict[str, float]
    weak_areas: typing.List[str]
    improvement_suggestions: typing.List[str]

class MutationResult(BaseModel):
    mutant_id: str
    status: typing.Union[typing_extensions.Literal['killed'], typing_extensions.Literal['survived'], typing_extensions.Literal['timeout'], typing_extensions.Literal['error']]
    execution_time_ms: int
    test_output: str
    failing_tests: typing.List[str]
    error_message: str

class MutationStrategy(BaseModel):
    target_functions: typing.List[str]
    recommended_operators: typing.List["MutationOperator"]
    priority_areas: typing.List[str]
    expected_mutant_count: int
    rationale: str

class UnitTestCase(BaseModel):
    name: str
    description: str
    test_code: str
    imports: typing.List[str]

# #########################################################################
# Generated type aliases (0)
# #########################################################################
