# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (0)
# #########################################################################

# #########################################################################
# Generated classes (4)
# #########################################################################

class CoverageImprovement(BaseModel):
    file_path: str
    function_name: str
    current_coverage_percentage: float
    suggestion_type: typing.Union[typing_extensions.Literal['missing_tests'], typing_extensions.Literal['edge_cases'], typing_extensions.Literal['error_handling']]
    priority: typing.Union[typing_extensions.Literal['low'], typing_extensions.Literal['medium'], typing_extensions.Literal['high']]
    suggested_tests: typing.List[str]
    code_examples: typing.List[str]

class CrashAnalysis(BaseModel):
    root_cause: str
    severity: typing.Union[typing_extensions.Literal['low'], typing_extensions.Literal['medium'], typing_extensions.Literal['high'], typing_extensions.Literal['critical']]
    suggested_fix: str
    additional_test_cases: typing.List[str]

class FuzzTestInput(BaseModel):
    args: typing.List[typing.Optional[typing.Union[str, int, float, bool]]]
    kwargs: typing.Dict[str, typing.Optional[typing.Union[str, int, float, bool]]]
    description: str
    expected_behavior: typing.Union[typing_extensions.Literal['normal'], typing_extensions.Literal['error'], typing_extensions.Literal['edge_case']]

class UnitTestCase(BaseModel):
    name: str
    description: str
    test_code: str
    imports: typing.List[str]

# #########################################################################
# Generated type aliases (0)
# #########################################################################
